[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/download/forge"
  to = "/.netlify/functions/download-forge"
  status = 200
  force = true

[[redirects]]
  from = "/download/forge-buddy"
  to = "/.netlify/functions/download-forge-buddy"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
